# Generated by Django 2.1.7 on 2019-03-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('answers', models.IntegerField(default=0)),
                ('correct_answer', models.CharField(default='Linus Torvalds', max_length=200)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('total_wrong_answers', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='Ftq_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1200)),
                ('image', models.ImageField(blank=True, upload_to='post_image')),
                ('knowledge_mastery', models.IntegerField(default=0)),
                ('knowledge_needs_improvement', models.IntegerField(default=0)),
                ('knowledge_black_hole', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ftq_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Mc_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('correct_answer', models.CharField(default='Linus Torvalds', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='Mc_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='mc_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unix_shells_quiz.Mc_Question'),
        ),
        migrations.AddField(
            model_name='ftq_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unix_shells_quiz.Ftq_Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unix_shells_quiz.Question'),
        ),
    ]
